FROM postgres:14.4

ENV PGUSER=postgres
ENV PGPASSWORD=postgres
ENV PGDATABASE=bia
ENV PGPORT=5432

RUN apt-get update

# RUN mkdir -p /home/db
# COPY ./database/db.sql /home/db

# RUN mkdir -p /scripts